[package]
edition.workspace = true
name = "rome_js_semantic"
version = "0.0.0"
authors.workspace = true
license.workspace = true
description = "Semantic model for the JavaScript language"
repository.workspace = true

[dependencies]
rome_rowan = { workspace = true }
rome_js_syntax = { path = "../rome_js_syntax" }
rust-lapper = "1.0.1"
rustc-hash = { workspace = true }

[dev-dependencies]
rome_markup = { path = "../rome_markup" }
rome_diagnostics = { workspace = true }
rome_console = { workspace = true }
rome_js_parser = { path = "../rome_js_parser" }
